//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace advent {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("advent.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advent of Code 2019 - C#/.NET Core 3.1\n======================================\n.
        /// </summary>
        internal static string Day_Header {
            get {
                return ResourceManager.GetString("Day.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part {0}:.
        /// </summary>
        internal static string Day_Part {
            get {
                return ResourceManager.GetString("Day.Part", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   {0}.
        /// </summary>
        internal static string Day_Part_Line {
            get {
                return ResourceManager.GetString("Day.Part.Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to value must be between 1 and 31.
        /// </summary>
        internal static string Help_InvalidDay {
            get {
                return ResourceManager.GetString("Help.InvalidDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to must specify day before loading input file.
        /// </summary>
        internal static string Help_SpecifyDay {
            get {
                return ResourceManager.GetString("Help.SpecifyDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usage: advent &lt;day&gt;.
        /// </summary>
        internal static string Help_Usage {
            get {
                return ResourceManager.GetString("Help.Usage", resourceCulture);
            }
        }
    }
}
